apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Chart.Name }}
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{ .Values.db.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
      containers:
        - env:
            - name: ENABLE_MIGRATION
              value: "y"
            - name: JF_ROUTER_ENTRYPOINTS_EXTERNALPORT
              value: "8082"
            - name: JF_SHARED_DATABASE_DRIVER
              value: org.postgresql.Driver
            - name: JF_SHARED_DATABASE_PASSWORD
              value: {{ .Values.db.password }}
            - name: JF_SHARED_DATABASE_TYPE
              value: postgresql
            - name: JF_SHARED_DATABASE_URL
              value: jdbc:postgresql://{{ .Values.db.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.db.port }}/{{ .Values.db.databaseName }}
            - name: JF_SHARED_DATABASE_USERNAME
              value: {{ .Values.db.user }}
            - name: JF_SHARED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: JF_SHARED_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: JF_SHARED_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
          image: releases-docker.jfrog.io/jfrog/artifactory-{{ .Values.artifactory.product }}:{{ .Chart.Version }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/jfrog/artifactory
              name: {{ .Chart.Name }}-data
      restartPolicy: Always
      volumes:
        - name: {{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-data
status: {}
