apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
{{- if .Values.tls.enabled }}
  tls:
  - secretName: {{ .Chart.Name }}-tls
{{- if .Values.tls.host }}
    hosts:
      - {{ .Values.tls.host }}
{{- end }}
{{- end }}
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Chart.Name }}
              port:
                number: 8082
{{- if and .Values.tls.enabled .Values.tls.host }}
    host: {{ .Values.tls.host }}
{{- end }}
