apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.db.serviceName }}
  name: {{ .Values.db.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.db.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Values.db.serviceName }}
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.db.databaseName }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
          image: releases-docker.jfrog.io/postgres:13.4-alpine
          name: postgresql
          ports:
            - containerPort: {{ .Values.db.port }}
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.db.serviceName }}-data
            - mountPath: /etc/localtime
              name: {{ .Values.db.serviceName }}-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: {{ .Values.db.serviceName }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.db.serviceName }}-data
        - name: {{ .Values.db.serviceName }}-claim1
          persistentVolumeClaim:
            claimName: {{ .Values.db.serviceName }}-claim1
            readOnly: true
status: {}
