apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: artifactory
  name: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: artifactory
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: artifactory
    spec:
      containers:
        - env:
            - name: ENABLE_MIGRATION
              value: "y"
            - name: JF_ROUTER_ENTRYPOINTS_EXTERNALPORT
              value: "8082"
            - name: JF_SHARED_DATABASE_DRIVER
              value: org.postgresql.Driver
            - name: JF_SHARED_DATABASE_PASSWORD
              value: password
            - name: JF_SHARED_DATABASE_TYPE
              value: postgresql
            - name: JF_SHARED_DATABASE_URL
              value: jdbc:postgresql://postgresql:5432/artifactory
            - name: JF_SHARED_DATABASE_USERNAME
              value: artifactory
            - name: JF_SHARED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: JF_SHARED_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: JF_SHARED_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
          image: releases-docker.jfrog.io/jfrog/artifactory-cpp-ce:7.38.10
          name: artifactory
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/jfrog/artifactory
              name: artifactory-data
      restartPolicy: Always
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: artifactory-data
status: {}
